title: Share2Learn
author: Sarfraaz Ahmed
email: 
description: > # this means to ignore newlines until "baseurl:"
  The best way to learn is to share what you learn

#pagination
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  asarfraaz # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-cayman
markdown: GFM
# The above line is added to fix the table displayed in https://asarfraaz.github.io/share2learn/tutorial/2021/10/05/str-methods.html
# Suggestion was from : https://github.com/pages-themes/cayman/issues/82#issuecomment-613750651
